import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { useState } from "react";
import { useApi } from "../services/api";
import jsPDF from "jspdf";

const t = {
  fr: {
    analyzed: "Document analysé",
    pages: "pages", words: "mots",
    completed: "✓ Complété",
    download_pdf: "📥 PDF",
    download_docx: "📄 DOCX",
    download_png: "🖼️ PNG",
    summary_title: "Résumé IA — GPT-4o",
    entities_title: "Entités extraites",
    ocr_title: "Texte extrait — OCR",
    qa_title: "Questions / Réponses",
    qa_placeholder: "Posez une question sur ce document...",
    ask: "Demander →",
    asking: "...",
    answer_title: "Réponse GPT-4o",
    entity_labels: { organizations: "Organisations", people: "Personnes", dates: "Dates", locations: "Lieux", amounts: "Montants" },
    report_title: "Rapport d'analyse",
    report_footer: "Généré par DocAnalyzer — Powered by Azure OpenAI GPT-4o × Eurastech",
    last_qa: "Dernière réponse Q&A",
    question_label: "Question",
  },
  en: {
    analyzed: "Analyzed document",
    pages: "pages", words: "words",
    completed: "✓ Completed",
    download_pdf: "📥 PDF",
    download_docx: "📄 DOCX",
    download_png: "🖼️ PNG",
    summary_title: "AI Summary — GPT-4o",
    entities_title: "Extracted entities",
    ocr_title: "Extracted text — OCR",
    qa_title: "Questions & Answers",
    qa_placeholder: "Ask a question about this document...",
    ask: "Ask →",
    asking: "...",
    answer_title: "GPT-4o Answer",
    entity_labels: { organizations: "Organizations", people: "People", dates: "Dates", locations: "Locations", amounts: "Amounts" },
    report_title: "Analysis Report",
    report_footer: "Generated by DocAnalyzer — Powered by Azure OpenAI GPT-4o × Eurastech",
    last_qa: "Last Q&A answer",
    question_label: "Question",
  },
  ar: {
    analyzed: "المستند المحلل",
    pages: "صفحات", words: "كلمات",
    completed: "✓ مكتمل",
    download_pdf: "📥 تحميل PDF",
    download_docx: "📄 تحميل DOCX",
    download_png: "🖼️ تحميل PNG",
    summary_title: "ملخص الذكاء الاصطناعي — GPT-4o",
    entities_title: "الكيانات المستخرجة",
    ocr_title: "النص المستخرج — OCR",
    qa_title: "الأسئلة والأجوبة",
    qa_placeholder: "اطرح سؤالاً حول هذا المستند...",
    ask: "اسأل →",
    asking: "...",
    answer_title: "إجابة GPT-4o",
    entity_labels: { organizations: "المنظمات", people: "الأشخاص", dates: "التواريخ", locations: "المواقع", amounts: "المبالغ" },
    report_title: "تقرير التحليل",
    report_footer: "تم إنشاؤه بواسطة DocAnalyzer — مدعوم بـ Azure OpenAI GPT-4o × Eurastech",
    last_qa: "آخر إجابة",
    question_label: "السؤال",
  },
};

export default function ResultCard({ result, isDark, lang = "fr" }) {
  const { askQuestion } = useApi();
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState(null);
  const [isAsking, setIsAsking] = useState(false);
  const [showOCR, setShowOCR] = useState(false);
  const text = t[lang] || t["fr"];

  const handleAsk = async () => {
    if (!question.trim()) return;
    setIsAsking(true);
    try {
      const res = await askQuestion(result.document_id, result.ocr_result.full_text, question);
      setAnswer(res.answer);
    } catch (e) { setAnswer("Error: " + e.message); }
    setIsAsking(false);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(99, 102, 241);
    doc.text(`DocAnalyzer — ${text.report_title}`, margin, y); y += 10;

    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y); y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`${result.original_filename}`, margin, y); y += 6;
    doc.text(`${result.ocr_result.page_count} ${text.pages} · ${result.ocr_result.word_count} ${text.words} · ${(result.size_bytes / 1024 / 1024).toFixed(2)} MB`, margin, y); y += 12;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(30, 30, 30);
    doc.text(text.summary_title, margin, y); y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const summaryLines = doc.splitTextToSize(result.ai_result.summary || "", maxWidth);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 5 + 12;

    if (result.ai_result.entities) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(30, 30, 30);
      doc.text(text.entities_title, margin, y); y += 8;

      Object.entries(result.ai_result.entities).forEach(([type, items]) => {
        if (!items?.length) return;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(99, 102, 241);
        doc.text(`${text.entity_labels[type]}:`, margin, y); y += 5;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(50, 50, 50);
        const line = doc.splitTextToSize(items.join(", "), maxWidth);
        doc.text(line, margin, y);
        y += line.length * 5 + 4;
      });
    }

    if (answer) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(30, 30, 30);
      doc.text(text.last_qa, margin, y); y += 8;
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text(`${text.question_label}: ${question}`, margin, y); y += 6;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(50, 50, 50);
      const answerLines = doc.splitTextToSize(answer, maxWidth);
      doc.text(answerLines, margin, y);
    }

    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(text.report_footer, margin, 285);
    doc.save(`rapport_${result.filename || "document"}.pdf`);
  };

  const handleDownloadDOCX = async () => {
    const doc = new Document({
      sections: [{
        children: [
          new Paragraph({ text: `DocAnalyzer — ${text.report_title}`, heading: HeadingLevel.HEADING_1 }),
          new Paragraph({ text: result.original_filename }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: text.summary_title, heading: HeadingLevel.HEADING_2 }),
          new Paragraph({ children: [new TextRun(result.ai_result?.summary || "")] }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: text.entities_title, heading: HeadingLevel.HEADING_2 }),
          ...Object.entries(result.ai_result?.entities || {}).flatMap(([type, items]) =>
            items?.length ? [
              new Paragraph({
                children: [
                  new TextRun({ text: `${text.entity_labels[type]}: `, bold: true }),
                  new TextRun(items.join(", ")),
                ],
              }),
            ] : []
          ),
          new Paragraph({ text: "" }),
          new Paragraph({
            children: [new TextRun({ text: text.report_footer, italics: true, color: "888888" })],
          }),
        ],
      }],
    });

    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `rapport_${result.filename || "document"}.docx`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPNG = () => {
    const canvas = document.createElement("canvas");
    canvas.width = 1200;
    canvas.height = 630;
    const ctx = canvas.getContext("2d");

    ctx.fillStyle = "#0A0F1E";
    ctx.fillRect(0, 0, 1200, 630);

    const grad = ctx.createLinearGradient(0, 0, 1200, 0);
    grad.addColorStop(0, "#6366F1");
    grad.addColorStop(1, "#06B6D4");
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, 1200, 6);

    ctx.fillStyle = "#F8FAFC";
    ctx.font = "bold 36px sans-serif";
    ctx.fillText("DocAnalyzer", 60, 80);

    ctx.fillStyle = "rgba(99,102,241,0.15)";
    ctx.roundRect(60, 100, 280, 32, 16);
    ctx.fill();
    ctx.fillStyle = "#818CF8";
    ctx.font = "13px sans-serif";
    ctx.fillText("Powered by Azure OpenAI GPT-4o", 76, 121);

    ctx.fillStyle = "#64748B";
    ctx.font = "16px sans-serif";
    ctx.fillText(result.original_filename, 60, 175);

    ctx.fillStyle = "#6366F1";
    ctx.font = "bold 14px sans-serif";
    ctx.fillText(text.summary_title.toUpperCase(), 60, 220);

    ctx.fillStyle = "#CBD5E1";
    ctx.font = "16px sans-serif";
    const summary = result.ai_result?.summary || "";
    const words = summary.split(" ");
    let line = "";
    let y = 248;
    for (const word of words) {
      const test = line + word + " ";
      if (ctx.measureText(test).width > 1080 || y > 480) break;
      if (ctx.measureText(test).width > 1080) {
        ctx.fillText(line, 60, y);
        line = word + " ";
        y += 26;
      } else {
        line = test;
      }
    }
    if (line) ctx.fillText(line, 60, y);

    ctx.fillStyle = "#334155";
    ctx.font = "13px sans-serif";
    ctx.fillText(text.report_footer, 60, 600);

    canvas.toBlob((blob) => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `rapport_${result.filename || "document"}.png`;
      a.click();
      URL.revokeObjectURL(url);
    });
  };

  const entityColors = {
    organizations: { bg: "rgba(99,102,241,0.1)", border: "rgba(99,102,241,0.25)", text: "var(--indigo)" },
    people:        { bg: "rgba(168,85,247,0.1)",  border: "rgba(168,85,247,0.25)",  text: "#A855F7" },
    dates:         { bg: "rgba(245,158,11,0.1)",  border: "rgba(245,158,11,0.25)",  text: "#D97706" },
    locations:     { bg: "rgba(16,185,129,0.1)",  border: "rgba(16,185,129,0.25)",  text: "#059669" },
    amounts:       { bg: "rgba(244,63,94,0.1)",   border: "rgba(244,63,94,0.25)",   text: "#E11D48" },
  };

  const docTypeConfig = {
    invoice:     { icon: "🧾", label: { fr: "Facture",            en: "Invoice",     ar: "فاتورة"      }, color: "#F59E0B" },
    contract:    { icon: "📜", label: { fr: "Contrat",            en: "Contract",    ar: "عقد"         }, color: "#6366F1" },
    cv:          { icon: "👤", label: { fr: "CV",                 en: "CV",          ar: "سيرة ذاتية"  }, color: "#8B5CF6" },
    report:      { icon: "📊", label: { fr: "Rapport",            en: "Report",      ar: "تقرير"       }, color: "#06B6D4" },
    id_document: { icon: "🪪", label: { fr: "Pièce d'identité",  en: "ID Document", ar: "وثيقة هوية"  }, color: "#10B981" },
    letter:      { icon: "📬", label: { fr: "Lettre",            en: "Letter",      ar: "رسالة"       }, color: "#EC4899" },
    unknown:     { icon: "❓", label: { fr: "Inconnu",           en: "Unknown",     ar: "غير معروف"   }, color: "#64748B" },
  };

  const card = {
    background: "var(--navy-card)", border: "1px solid var(--navy-border)",
    borderRadius: "20px", padding: "24px", marginBottom: "0",
  };

  // Resolve doc type badge
  const dtype = result.ai_result?.document_type;
  const dtypeCfg = dtype ? (docTypeConfig[dtype] || docTypeConfig["unknown"]) : null;

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>

      {/* Header */}
      <div style={{ ...card, display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "12px" }}>
        <div>
          <div style={{
            fontSize: "11px", fontWeight: "700", color: "var(--indigo)",
            letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "8px",
          }}>{text.analyzed}</div>
          <h2 style={{
            fontFamily: "var(--font-display)", fontSize: "20px",
            fontWeight: "700", color: "var(--text-primary)", marginBottom: "8px",
          }}>{result.original_filename}</h2>
          <div style={{ display: "flex", gap: "16px", flexWrap: "wrap" }}>
            {[
              { icon: "📄", value: `${result.ocr_result.page_count} ${text.pages}` },
              { icon: "📝", value: `${result.ocr_result.word_count} ${text.words}` },
              { icon: "💾", value: `${(result.size_bytes / 1024 / 1024).toFixed(2)} MB` },
            ].map((s, i) => (
              <span key={i} style={{ fontSize: "13px", color: "var(--text-muted)" }}>{s.icon} {s.value}</span>
            ))}
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: "10px" }}>

          {/* Document type badge */}
          {dtypeCfg && (
            <span style={{
              background: `${dtypeCfg.color}18`,
              border: `1px solid ${dtypeCfg.color}40`,
              color: dtypeCfg.color,
              borderRadius: "20px", padding: "5px 14px",
              fontSize: "13px", fontWeight: "600",
              display: "flex", alignItems: "center", gap: "6px",
            }}>
              {dtypeCfg.icon} {dtypeCfg.label[lang] || dtypeCfg.label["en"]}
            </span>
          )}

          {/* Completed badge */}
          <span style={{
            background: "rgba(16,185,129,0.1)", border: "1px solid rgba(16,185,129,0.25)",
            color: "var(--green)", borderRadius: "20px", padding: "5px 14px",
            fontSize: "13px", fontWeight: "600",
          }}>{text.completed}</span>

          {/* Download buttons */}
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
            <button onClick={handleDownloadPDF} style={{
              display: "flex", alignItems: "center", gap: "6px",
              padding: "8px 14px", borderRadius: "10px", border: "none",
              background: "linear-gradient(135deg, var(--indigo), #4F46E5)",
              color: "white", cursor: "pointer",
              fontSize: "13px", fontWeight: "600", fontFamily: "var(--font-body)",
              boxShadow: "0 0 16px rgba(99,102,241,0.2)", transition: "all 0.2s",
            }}>{text.download_pdf}</button>

            <button onClick={handleDownloadDOCX} style={{
              display: "flex", alignItems: "center", gap: "6px",
              padding: "8px 14px", borderRadius: "10px",
              border: "1.5px solid rgba(99,102,241,0.3)",
              background: "rgba(99,102,241,0.08)",
              color: "var(--indigo)", cursor: "pointer",
              fontSize: "13px", fontWeight: "600", fontFamily: "var(--font-body)",
              transition: "all 0.2s",
            }}>{text.download_docx}</button>

            <button onClick={handleDownloadPNG} style={{
              display: "flex", alignItems: "center", gap: "6px",
              padding: "8px 14px", borderRadius: "10px",
              border: "1.5px solid rgba(6,182,212,0.3)",
              background: "rgba(6,182,212,0.08)",
              color: "var(--cyan)", cursor: "pointer",
              fontSize: "13px", fontWeight: "600", fontFamily: "var(--font-body)",
              transition: "all 0.2s",
            }}>{text.download_png}</button>
          </div>
        </div>
      </div>

      {/* Summary */}
      <div style={card}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "16px" }}>
          <div style={{
            width: "32px", height: "32px", borderRadius: "8px",
            background: "linear-gradient(135deg, var(--indigo), var(--cyan))",
            display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px",
          }}>🧠</div>
          <span style={{ fontFamily: "var(--font-display)", fontWeight: "700", fontSize: "15px", color: "var(--text-primary)" }}>
            {text.summary_title}
          </span>
        </div>
        <p style={{
          color: "var(--text-soft)", lineHeight: "1.8", fontSize: "15px",
          borderLeft: "3px solid var(--indigo)", paddingLeft: "16px",
        }}>{result.ai_result.summary}</p>
      </div>

      {/* Entities */}
      {result.ai_result.entities && Object.keys(result.ai_result.entities).some(k => result.ai_result.entities[k]?.length > 0) && (
        <div style={card}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "16px" }}>
            <div style={{
              width: "32px", height: "32px", borderRadius: "8px",
              background: "rgba(245,158,11,0.15)", border: "1px solid rgba(245,158,11,0.25)",
              display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px",
            }}>🏷️</div>
            <span style={{ fontFamily: "var(--font-display)", fontWeight: "700", fontSize: "15px", color: "var(--text-primary)" }}>
              {text.entities_title}
            </span>
          </div>
          {Object.entries(entityColors).map(([type, colors]) => {
            const items = result.ai_result.entities[type];
            if (!items?.length) return null;
            return (
              <div key={type} style={{ marginBottom: "12px" }}>
                <div style={{ fontSize: "11px", fontWeight: "700", color: "var(--text-muted)", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: "8px" }}>
                  {text.entity_labels[type]}
                </div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
                  {items.map((item, i) => (
                    <span key={i} style={{
                      background: colors.bg, border: `1px solid ${colors.border}`,
                      color: colors.text, borderRadius: "8px",
                      padding: "4px 12px", fontSize: "13px", fontWeight: "500",
                    }}>{item}</span>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* OCR Collapsible */}
      <div style={{ ...card, padding: "0", overflow: "hidden" }}>
        <button
          onClick={() => setShowOCR(!showOCR)}
          style={{
            width: "100%", padding: "20px 24px",
            display: "flex", alignItems: "center", justifyContent: "space-between",
            background: "transparent", border: "none", cursor: "pointer", transition: "background 0.2s",
          }}
          onMouseEnter={e => e.currentTarget.style.background = "rgba(99,102,241,0.04)"}
          onMouseLeave={e => e.currentTarget.style.background = "transparent"}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            <div style={{
              width: "32px", height: "32px", borderRadius: "8px",
              background: "rgba(6,182,212,0.1)", border: "1px solid rgba(6,182,212,0.25)",
              display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px",
            }}>📝</div>
            <span style={{ fontFamily: "var(--font-display)", fontWeight: "700", fontSize: "15px", color: "var(--text-primary)" }}>
              {text.ocr_title}
            </span>
            <span style={{ fontSize: "11px", color: "var(--text-muted)", background: "var(--navy-border)", borderRadius: "6px", padding: "2px 8px" }}>
              {result.ocr_result.word_count} {text.words}
            </span>
          </div>
          <span style={{
            color: "var(--text-muted)", fontSize: "16px",
            transform: showOCR ? "rotate(180deg)" : "rotate(0deg)",
            transition: "transform 0.3s", display: "inline-block",
          }}>▼</span>
        </button>
        {showOCR && (
          <div style={{ padding: "0 24px 24px" }}>
            <pre style={{
              background: "var(--navy)", border: "1px solid var(--navy-border)",
              borderRadius: "12px", padding: "16px",
              fontSize: "12px", color: "var(--text-muted)",
              maxHeight: "220px", overflowY: "auto",
              whiteSpace: "pre-wrap", fontFamily: "'Courier New', monospace",
              lineHeight: "1.7",
            }}>{result.ocr_result.full_text}</pre>
          </div>
        )}
      </div>

      {/* Q&A */}
      <div style={card}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "20px" }}>
          <div style={{
            width: "32px", height: "32px", borderRadius: "8px",
            background: "rgba(168,85,247,0.1)", border: "1px solid rgba(168,85,247,0.25)",
            display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px",
          }}>❓</div>
          <span style={{ fontFamily: "var(--font-display)", fontWeight: "700", fontSize: "15px", color: "var(--text-primary)" }}>
            {text.qa_title}
          </span>
        </div>
        <div style={{ display: "flex", gap: "10px" }}>
          <input
            type="text"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleAsk()}
            placeholder={text.qa_placeholder}
            dir={lang === "ar" ? "rtl" : "ltr"}
            style={{
              flex: 1, padding: "12px 16px",
              background: "var(--navy)", border: "1px solid var(--navy-border)",
              borderRadius: "12px", color: "var(--text-primary)",
              fontSize: "14px", fontFamily: "var(--font-body)", outline: "none",
              transition: "border-color 0.2s",
            }}
            onFocus={e => e.target.style.borderColor = "var(--indigo)"}
            onBlur={e => e.target.style.borderColor = "var(--navy-border)"}
          />
          <button
            onClick={handleAsk}
            disabled={isAsking || !question.trim()}
            style={{
              padding: "12px 24px", borderRadius: "12px", border: "none",
              background: isAsking || !question.trim() ? "var(--navy-border)" : "linear-gradient(135deg, var(--indigo), #4F46E5)",
              color: "white", cursor: isAsking || !question.trim() ? "not-allowed" : "pointer",
              fontSize: "14px", fontWeight: "600", fontFamily: "var(--font-body)",
              transition: "all 0.2s", whiteSpace: "nowrap",
            }}
          >{isAsking ? text.asking : text.ask}</button>
        </div>
        {answer && (
          <div style={{
            marginTop: "16px", background: "rgba(99,102,241,0.06)",
            border: "1px solid rgba(99,102,241,0.18)", borderRadius: "12px", padding: "16px",
          }}>
            <div style={{ fontSize: "11px", fontWeight: "700", color: "var(--indigo)", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: "8px" }}>
              {text.answer_title}
            </div>
            <p style={{ color: "var(--text-soft)", lineHeight: "1.7", fontSize: "14px" }}>{answer}</p>
          </div>
        )}
      </div>
    </div>
  );
}